import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync} from 'node:fs';
const route=readFileSync(new URL('../app/api/webhooks/dodo/route.ts',import.meta.url),'utf8');
// Exercise the real award statements from the route against SQLite, not mirrored SQL.
const awardSQL=[...route.matchAll(/db\(\)\.prepare\("([^"]+)"\)/g)].map(m=>m[1]).filter(s=>s.startsWith('UPDATE slots SET owner_id')||s.startsWith("UPDATE orders SET status='paid'")||s.startsWith('INSERT OR IGNORE INTO refund_jobs (payment,order_id,mode,status,created) SELECT')||s.startsWith("UPDATE orders SET status='outbid'"));
function setup(){const db=new DatabaseSync(':memory:');for(const f of readdirSync(new URL('../drizzle/',import.meta.url)).filter(f=>f.endsWith('.sql')).sort())db.exec(readFileSync(new URL(`../drizzle/${f}`,import.meta.url),'utf8'));db.exec('INSERT INTO slots(id,version,paid,reserved_until) VALUES(0,0,0,0)');return db;}
function order(db,id,previous=null,version=0,amount=1000){db.prepare("INSERT INTO orders(id,slot,amount,brand,tagline,website,token_hash,status,expires,created,expected_version,previous_id) VALUES(?,0,?,'Test','Test','https://example.com',?,'pending',9999,0,?,?)").run(id,amount,id,version,previous);}
function award(db,id,payment,version,previous=null,now=1,close=100){assert.equal(awardSQL.length,4);db.exec('BEGIN');try{const args=[[id,0,id,version,now,close,id],[payment,id,0,id],[now,previous,0,id],[previous,0,id]];awardSQL.forEach((sql,i)=>db.prepare(sql).run(...args[i]));db.exec('COMMIT');}catch(e){db.exec('ROLLBACK');throw e;}}
test('first paid bid owns a spot; replay changes nothing',()=>{const db=setup();order(db,'a');db.prepare('UPDATE slots SET order_id=?').run('a');award(db,'a','pay_a',0);award(db,'a','pay_a',0);assert.equal(db.prepare('SELECT version FROM slots').get().version,1);assert.equal(db.prepare('SELECT status FROM orders').get().status,'paid');assert.equal(db.prepare('SELECT count(*) n FROM refund_jobs').get().n,0);});
test('takeover atomically changes owner and creates one refund job for previous owner',()=>{const db=setup();order(db,'a');db.prepare('UPDATE slots SET order_id=?').run('a');award(db,'a','pay_a',0);order(db,'b','a',1,2000);db.prepare('UPDATE slots SET order_id=?').run('b');award(db,'b','pay_b',1,'a');award(db,'b','pay_b',1,'a');assert.equal(db.prepare('SELECT owner_id FROM slots').get().owner_id,'b');assert.equal(db.prepare("SELECT status FROM orders WHERE id='a'").get().status,'outbid');assert.equal(db.prepare('SELECT count(*) n FROM refund_jobs').get().n,1);assert.equal(db.prepare('SELECT payment,mode FROM refund_jobs').get().payment,'pay_a');});
test('expired checkout cannot take a newly reserved spot',()=>{const db=setup();order(db,'a');order(db,'b');db.prepare('UPDATE slots SET order_id=?').run('b');award(db,'a','pay_a',0);assert.equal(db.prepare('SELECT owner_id FROM slots').get().owner_id,null);assert.equal(db.prepare("SELECT status FROM orders WHERE id='a'").get().status,'pending');});
test('stale version and payment after auction close cannot win',()=>{for(const [version,now] of [[1,1],[0,101]]){const db=setup();order(db,'a');db.prepare('UPDATE slots SET order_id=?').run('a');award(db,'a','pay_a',version,null,now);assert.equal(db.prepare('SELECT owner_id FROM slots').get().owner_id,null);}});
test('concurrent checkout locks permit only one reservation per version',()=>{const db=setup();const sql=readFileSync(new URL('../app/api/checkout/route.ts',import.meta.url),'utf8').match(/prepare\('(UPDATE slots SET order_id=[^']+)'\)/)[1];const a=db.prepare(sql).run('a',100,0,0,1);const b=db.prepare(sql).run('b',100,0,0,1);assert.equal(a.changes,1);assert.equal(b.changes,0);});
test('payment identity is unique across bids',()=>{const db=setup();order(db,'a');order(db,'b');db.prepare('UPDATE orders SET payment=? WHERE id=?').run('pay_a','a');assert.throws(()=>db.prepare('UPDATE orders SET payment=? WHERE id=?').run('pay_a','b'));});
import ts from 'typescript';
async function sourceModule(path){const js=ts.transpileModule(readFileSync(new URL(path,import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext}}).outputText;return import(`data:text/javascript;base64,${Buffer.from(js).toString('base64')}`);}
const {nextPrice}=await sourceModule('../lib/config.ts');
const {refundAfterFees}=await sourceModule('../lib/refund-math.ts');
test('regular spots open at $10, butt at $20, and both double',()=>{for(let n=0;n<8;n++)assert.equal(nextPrice(n),1000);assert.equal(nextPrice(8),2000);assert.equal(nextPrice(0,1000),2000);assert.equal(nextPrice(8,2000),4000);assert.equal(nextPrice(8,4000),8000);});
test('refund uses actual USD fees, includes original tax in refund base, and nets fee credits',()=>{assert.deepEqual(refundAfterFees(1180,'pay_a',[{amount:85,is_credit:false,currency:'USD',reference_object_id:'pay_a'},{amount:10,is_credit:true,currency:'USD',reference_object_id:'pay_a'}]),{amount:1105,fee:75});});
test('missing, mismatched, and impossible fees cannot produce a guessed refund',()=>{assert.throws(()=>refundAfterFees(1000,'pay_a',[]));for(const extra of [{currency:'INR'},{reference_object_id:'pay_other'},{amount:1001},{amount:5,is_credit:true}])assert.throws(()=>refundAfterFees(1000,'pay_a',[{amount:85,is_credit:false,currency:'USD',reference_object_id:'pay_a',...extra}]));});
