import {db,dodo,error,settings,readBody,type Order} from '@/lib/server';
import {CLOSE_DATE} from '@/lib/config';
import {drainRefunds} from '@/lib/refunds';
export async function POST(req:Request){if(!settings().DODO_PAYMENTS_WEBHOOK_KEY)return error('Payments are not configured.',503);let event;try{const body=new TextDecoder().decode(await readBody(req,256000));event=dodo().webhooks.unwrap(body,{headers:Object.fromEntries(req.headers)});}catch{return error('Invalid webhook signature.',400);}
try{if(event.type==='refund.succeeded'||event.type==='refund.failed'){const refund=event.data as {refund_id?:string;payment_id?:string;metadata?:Record<string,string>};const payment=refund.payment_id??refund.metadata?.payment;if(refund.refund_id&&/^[A-Za-z0-9_]+$/.test(refund.refund_id)&&payment&&refund.metadata?.project==='slow-club'){const {error:refundError}=await db().from('slowrun_refund_jobs').update({status:event.type==='refund.succeeded'?'succeeded':'failed',refund_id:refund.refund_id}).eq('payment',payment).or(`refund_id.is.null,refund_id.eq.${refund.refund_id}`).neq('status','succeeded');if(refundError)throw refundError;}return Response.json({received:true});}
if(event.type!=='payment.succeeded')return Response.json({received:true});const data=event.data as {payment_id?:string;metadata?:Record<string,string>};if(data.metadata?.project!=='slow-club')return Response.json({received:true});const {data:order,error:orderError}=await db().from('slowrun_orders').select('*').eq('id',data.metadata.orderId??'').maybeSingle<Order>();if(orderError)throw orderError;if(!order||!data.payment_id)return error('Unknown payment order.',400);
if(order.payment===data.payment_id&&order.status!=='pending'){await drainRefunds();return Response.json({received:true});}
const payment=await dodo().payments.retrieve(data.payment_id,{timeout:10000,maxRetries:1});if(payment.status!=='succeeded'||payment.currency!=='USD'||payment.metadata?.orderId!==order.id||payment.product_cart?.length!==1||payment.product_cart[0].product_id!==settings().DODO_PAYMENTS_PRODUCT_ID||payment.product_cart[0].quantity!==1||payment.total_amount-(payment.tax??0)!==order.amount)return error('Payment does not match order.',400);
// Ownership transfer, outbid marking and refund queueing happen atomically inside Postgres.
const {data:outcome,error:awardError}=await db().rpc('slowrun_award_payment',{p_order_id:order.id,p_payment:data.payment_id,p_now:Date.now(),p_close:Date.parse(CLOSE_DATE)});if(awardError)throw awardError;if(outcome==='unknown')return error('Unknown payment order.',400);
await drainRefunds();return Response.json({received:true});
}catch{return error('Payment processing is temporarily unavailable. Please retry.',500);}}
