import {db,dodo,error,settings,readBody,type Order} from '@/lib/server';
import {CLOSE_DATE} from '@/lib/config';
import {drainRefunds} from '@/lib/refunds';
export async function POST(req:Request){if(!settings().DODO_PAYMENTS_WEBHOOK_KEY)return error('Payments are not configured.',503);let event;try{const body=new TextDecoder().decode(await readBody(req,256000));event=dodo().webhooks.unwrap(body,{headers:Object.fromEntries(req.headers)});}catch{return error('Invalid webhook signature.',400);}
try{if(event.type==='refund.succeeded'||event.type==='refund.failed'){const refund=event.data as {refund_id?:string;payment_id?:string;metadata?:Record<string,string>};if(refund.refund_id&&refund.metadata?.project==='slow-club'){await db().prepare("UPDATE refund_jobs SET status=?,refund_id=? WHERE payment=? AND (refund_id IS NULL OR refund_id=?) AND status!='succeeded'").bind(event.type==='refund.succeeded'?'succeeded':'failed',refund.refund_id,refund.payment_id??refund.metadata.payment,refund.refund_id).run();}return Response.json({received:true});}
if(event.type!=='payment.succeeded')return Response.json({received:true});const data=event.data as {payment_id?:string;metadata?:Record<string,string>};if(data.metadata?.project!=='slow-club')return Response.json({received:true});const order=await db().prepare('SELECT * FROM orders WHERE id=?').bind(data.metadata.orderId??'').first<Order>();if(!order||!data.payment_id)return error('Unknown payment order.',400);
if(order.payment===data.payment_id&&order.status!=='pending'){await drainRefunds();return Response.json({received:true});}
const payment=await dodo().payments.retrieve(data.payment_id,{timeout:10000,maxRetries:1});if(payment.status!=='succeeded'||payment.currency!=='USD'||payment.metadata?.orderId!==order.id||payment.product_cart?.length!==1||payment.product_cart[0].product_id!==settings().DODO_PAYMENTS_PRODUCT_ID||payment.product_cart[0].quantity!==1||payment.total_amount-(payment.tax??0)!==order.amount)return error('Payment does not match order.',400);
const now=Date.now();await db().batch([
db().prepare("UPDATE slots SET owner_id=?,paid=1,reserved_until=0,version=version+1 WHERE id=? AND order_id=? AND version=? AND ?<? AND EXISTS(SELECT 1 FROM orders WHERE id=? AND status='pending')").bind(order.id,order.slot,order.id,order.expected_version,now,Date.parse(CLOSE_DATE),order.id),
db().prepare("UPDATE orders SET status='paid',payment=? WHERE id=? AND status='pending' AND EXISTS(SELECT 1 FROM slots WHERE id=? AND owner_id=?)").bind(data.payment_id,order.id,order.slot,order.id),
db().prepare("INSERT OR IGNORE INTO refund_jobs (payment,order_id,mode,status,created) SELECT payment,id,'outbid','pending',? FROM orders WHERE id=? AND status='paid' AND EXISTS(SELECT 1 FROM slots WHERE id=? AND owner_id=?)").bind(now,order.previous_id,order.slot,order.id),
db().prepare("UPDATE orders SET status='outbid' WHERE id=? AND status='paid' AND EXISTS(SELECT 1 FROM slots WHERE id=? AND owner_id=?)").bind(order.previous_id,order.slot,order.id)
]);
const applied=await db().prepare('SELECT status,payment FROM orders WHERE id=?').bind(order.id).first<{status:string;payment:string}>();if(applied?.payment!==data.payment_id){await db().batch([db().prepare("INSERT OR IGNORE INTO refund_jobs (payment,order_id,mode,status,created) VALUES (?,?,'unfulfilled','pending',?)").bind(data.payment_id,order.id,now),db().prepare("UPDATE orders SET status='unfulfilled',payment=? WHERE id=? AND status='pending'").bind(data.payment_id,order.id)]);}
await drainRefunds();return Response.json({received:true});
}catch{return error('Payment processing is temporarily unavailable. Please retry.',500);}}
