'use client';
import {useEffect,useRef,useState} from 'react';
import type {Sponsor} from '@/lib/config';
import {buildRaceStart} from './RaceStart';
export default function Arena({sponsors,selected,onSelect,view,accent}:{sponsors:Sponsor[];selected:number;onSelect:(n:number)=>void;view:'front'|'back';accent:string}){
const container=useRef<HTMLDivElement>(null);const [failed,setFailed]=useState(false);const latest=useRef({sponsors,selected,onSelect,view,accent});latest.current={sponsors,selected,onSelect,view,accent};
useEffect(()=>{let cleanup=()=>{};let cancelled=false;
async function init(){try{const THREE=await import('three');const {OrbitControls}=await import('three/examples/jsm/controls/OrbitControls.js');if(cancelled||!container.current)return;const host=container.current;const scene=new THREE.Scene();scene.background=new THREE.Color('#100908');scene.fog=new THREE.FogExp2('#100908',.035);
const camera=new THREE.PerspectiveCamera(35,host.clientWidth/host.clientHeight,.1,100);const distance=()=>host.clientWidth<640?12.5:9.4;camera.position.set(0,2.7,distance());const renderer=new THREE.WebGLRenderer({antialias:true,alpha:false});renderer.setPixelRatio(Math.min(window.devicePixelRatio,1.7));renderer.setSize(host.clientWidth,host.clientHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;host.appendChild(renderer.domElement);renderer.domElement.setAttribute('aria-label','Interactive 3D race-shirt mannequin. Drag to rotate; scroll to zoom. Choose spots with the View spots button.');
const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,1.9,0);controls.enablePan=false;controls.enableDamping=true;controls.minDistance=5.7;controls.maxDistance=12;controls.minPolarAngle=.9;controls.maxPolarAngle=1.6;
scene.add(new THREE.HemisphereLight('#fff3df','#8e947c',2.5));const key=new THREE.DirectionalLight('#ffedcb',3);key.position.set(-3,7,5);key.castShadow=true;key.shadow.mapSize.set(1024,1024);scene.add(key);const rim=new THREE.PointLight('#ffd6a0',.5,14);rim.position.set(2,3,-2);scene.add(rim);const fill=new THREE.PointLight('#dce9ed',2,10);fill.position.set(-3,3,2);scene.add(fill);
const accentMaterial=new THREE.MeshBasicMaterial({color:latest.current.accent});const skin=new THREE.MeshStandardMaterial({color:'#777572',roughness:.85});const tee=new THREE.MeshStandardMaterial({color:'#f1efe5',roughness:1});const shorts=new THREE.MeshStandardMaterial({color:'#1d2125',roughness:1});const shoes=new THREE.MeshStandardMaterial({color:'#e8e5dc',roughness:.8});const runner=new THREE.Group();runner.position.y=.23;scene.add(runner);
function mesh(geometry:import('three').BufferGeometry,material:InstanceType<typeof THREE.Material>,x:number,y:number,z:number,parent:InstanceType<typeof THREE.Object3D>=runner){const m=new THREE.Mesh(geometry,material);m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m;}
function ellipsoid(x:number,y:number,z:number,sx:number,sy:number,sz:number,material:InstanceType<typeof THREE.Material>){const m=mesh(new THREE.SphereGeometry(1,32,24),material,x,y,z);m.scale.set(sx,sy,sz);return m;}
function limb(a:number[],b:number[],r:number,material:InstanceType<typeof THREE.Material>){const from=new THREE.Vector3(...a),to=new THREE.Vector3(...b),v=to.clone().sub(from);const m=mesh(new THREE.CapsuleGeometry(r,Math.max(.01,v.length()-r*2),8,16),material,...from.clone().add(to).multiplyScalar(.5).toArray() as [number,number,number]);m.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),v.normalize());return m;}
// Deliberately neutral mannequin, not a claimed likeness of the runner.
ellipsoid(0,3.58,0,.24,.32,.245,skin);ellipsoid(0,3.55,.238,.055,.08,.05,skin);ellipsoid(-.243,3.58,0,.04,.085,.05,skin);ellipsoid(.243,3.58,0,.04,.085,.05,skin);limb([0,3.1,0],[0,3.4,0],.115,skin);
const torso=mesh(new THREE.CylinderGeometry(.46,.4,.95,48),tee,0,2.77,0);torso.scale.z=.59;ellipsoid(0,3.18,0,.45,.13,.265,tee);
for(const sign of [-1,1]){limb([sign*.38,3.12,0],[sign*.57,2.84,0],.19,tee);limb([sign*.57,2.83,0],[sign*.68,2.42,.015],.125,skin);limb([sign*.68,2.42,.015],[sign*.73,1.99,.11],.10,skin);ellipsoid(sign*.73,1.96,.12,.105,.15,.095,skin);const leg=mesh(new THREE.CylinderGeometry(.23,.20,.50,24),shorts,sign*.225,2.03,0);leg.scale.z=1.13;limb([sign*.23,1.86,0],[sign*.25,1.13,.015],.155,skin);limb([sign*.25,1.10,.015],[sign*.26,.35,.035],.11,skin);limb([sign*.26,.42,.035],[sign*.26,.24,.035],.115,shoes);ellipsoid(sign*.26,.14,.16,.155,.13,.31,shoes);const sole=ellipsoid(sign*.26,.07,.16,.158,.048,.315,accentMaterial);sole.castShadow=false;}
const waist=mesh(new THREE.CylinderGeometry(.405,.4,.18,40),shorts,0,2.27,0);waist.scale.z=.63;
const disposeEnvironment=buildRaceStart(scene, THREE);
const patches:InstanceType<typeof THREE.Mesh>[]=[];const positions=[[0,2.70,.275,.52,.25,0],[-.23,3.02,.253,.26,.16,0],[.23,3.02,.253,.26,.16,0],[-.58,2.99,.155,.23,.18,-.45],[.58,2.99,.155,.23,.18,.45],[0,3.04,-.274,.52,.20,Math.PI],[0,2.76,-.275,.52,.24,Math.PI],[0,2.46,-.26,.52,.19,Math.PI],[0,2.09,-.257,.48,.22,Math.PI]];
let signature='';const textures:InstanceType<typeof THREE.Texture>[]=[];
function updatePatches(){for(const t of textures)t.dispose();textures.length=0;for(const p of patches){runner.remove(p);p.geometry.dispose();(p.material as InstanceType<typeof THREE.Material>).dispose();}patches.length=0;positions.forEach(([x,y,z,w,h,rotation],n)=>{const canvas=document.createElement('canvas');canvas.width=512;canvas.height=256;const ctx=canvas.getContext('2d')!;const sponsor=latest.current.sponsors.find(s=>s.slot===n);ctx.fillStyle=n===latest.current.selected?latest.current.accent:'#e5e5dd';ctx.fillRect(0,0,512,256);ctx.strokeStyle='#44483c';ctx.lineWidth=5;ctx.setLineDash([15,10]);ctx.strokeRect(8,8,496,240);ctx.fillStyle='#24241e';ctx.textAlign='center';ctx.textBaseline='middle';ctx.font='bold 50px Arial';ctx.fillText(sponsor?sponsor.brand.slice(0,15):n===0?'YOUR LOGO':`+ 0${n+1}`,256,128);const tex=new THREE.CanvasTexture(canvas);tex.colorSpace=THREE.SRGBColorSpace;textures.push(tex);if(sponsor?.logo){const image=new Image();image.onload=()=>{if(cancelled)return;ctx.fillStyle='#fafaf6';ctx.fillRect(0,0,512,256);const scale=Math.min(470/image.width,220/image.height);ctx.drawImage(image,(512-image.width*scale)/2,(256-image.height*scale)/2,image.width*scale,image.height*scale);tex.needsUpdate=true;};image.src=sponsor.logo;}const p=mesh(new THREE.PlaneGeometry(w,h),new THREE.MeshStandardMaterial({map:tex,roughness:1,polygonOffset:true,polygonOffsetFactor:-2}),x,y,z);p.rotation.y=rotation;p.userData.slot=n;patches.push(p);});}
const raycaster=new THREE.Raycaster();let start={x:0,y:0};const down=(e:PointerEvent)=>{start={x:e.clientX,y:e.clientY}};const click=(e:PointerEvent)=>{if(Math.hypot(e.clientX-start.x,e.clientY-start.y)>8)return;const rect=renderer.domElement.getBoundingClientRect();raycaster.setFromCamera(new THREE.Vector2((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1),camera);const hits=raycaster.intersectObjects(patches);if(hits[0])latest.current.onSelect(hits[0].object.userData.slot);};renderer.domElement.addEventListener('pointerdown',down);renderer.domElement.addEventListener('pointerup',click);
const resize=new ResizeObserver(()=>{camera.aspect=host.clientWidth/host.clientHeight;camera.updateProjectionMatrix();renderer.setSize(host.clientWidth,host.clientHeight);});resize.observe(host);let oldView=latest.current.view;runner.rotation.y=0;let frame=0;let visible=true;const visibility=()=>{visible=!document.hidden};document.addEventListener('visibilitychange',visibility);function animate(){frame=requestAnimationFrame(animate);if(!visible)return;const state=latest.current;const sig=JSON.stringify([state.sponsors,state.selected,state.accent]);if(sig!==signature){signature=sig;accentMaterial.color.set(state.accent);updatePatches();}if(oldView!==state.view){oldView=state.view;camera.position.set(0,2.7,state.view==='back'?-distance():distance());controls.update();}controls.update();renderer.render(scene,camera);}animate();cleanup=()=>{cancelAnimationFrame(frame);resize.disconnect();document.removeEventListener('visibilitychange',visibility);controls.dispose();renderer.domElement.removeEventListener('pointerdown',down);renderer.domElement.removeEventListener('pointerup',click);scene.traverse(o=>{if(o instanceof THREE.Mesh){o.geometry.dispose();const materials=Array.isArray(o.material)?o.material:[o.material];materials.forEach(m=>m.dispose());}});textures.forEach(t=>t.dispose());disposeEnvironment();renderer.dispose();renderer.domElement.remove();};}catch{if(!cancelled)setFailed(true);}}
void init();return()=>{cancelled=true;cleanup();};},[]);
return <div ref={container} className="arena">{failed&&<div className="scene-fallback"><strong>21.1</strong><p>The 3D preview isn’t available on this device.</p><button onClick={()=>onSelect(0)}>Explore the shirt spots ↗</button></div>}</div>}
