'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {CLOSE_DATE,SPOTS,nextPrice,type Sponsor} from '@/lib/config';
import {REFUND_NETWORKS,parseRefundWallet,type RefundNetwork} from '@/lib/wallet';
import {confetti} from './Confetti';
const TOKEN_KEY='slow-club-checkout-token';
type Refund={status:string;amount:number|null;fee:number|null;network:string|null;address:string|null;reference:string|null;referenceUrl:string|null};
type OrderState={status:string;brand:string;slot:number;logo:string;stablecoin:boolean;refundWallet:{network:string;address:string}|null;refund:Refund|null};
function makeToken(){return Array.from(crypto.getRandomValues(new Uint8Array(32)),b=>b.toString(16).padStart(2,'0')).join('');}
const usd=(cents:number)=>`$${(cents/100).toFixed(2)}`;
const networkName=(network:string|null)=>network&&Object.hasOwn(REFUND_NETWORKS,network)?REFUND_NETWORKS[network as RefundNetwork]:'its network';
/** Network, address and an ownership confirmation for a stablecoin refund wallet. */
function WalletFields({network,onNetwork,disabled=false}:{network:RefundNetwork;onNetwork:(network:RefundNetwork)=>void;disabled?:boolean}){return <div className="wallet-fields"><label>Refund network<select name="refundNetwork" value={network} disabled={disabled} onChange={event=>onNetwork(event.target.value as RefundNetwork)}>{Object.entries(REFUND_NETWORKS).map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label><label>Refund wallet address<input name="refundAddress" required disabled={disabled} maxLength={64} autoComplete="off" autoCapitalize="off" spellCheck={false} placeholder={network==='solana'?'Solana wallet address':'0x… wallet address'}/></label><label className="check"><input name="walletConfirmed" type="checkbox" required disabled={disabled}/>I control this wallet on {REFUND_NETWORKS[network]}. It isn’t an exchange deposit address.</label></div>;}
/** Lets a stablecoin payer add a refund wallet after checkout, e.g. when their refund is waiting for one. */
function RefundWalletForm({getToken,onSaved}:{getToken:()=>string;onSaved:()=>void}){const [network,setNetwork]=useState<RefundNetwork>('base'),[saving,setSaving]=useState(false),[note,setNote]=useState('');
async function save(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const fd=new FormData(event.currentTarget);const wallet=parseRefundWallet(fd.get('refundNetwork'),fd.get('refundAddress'));if(!wallet){setNote('Enter a valid wallet address for the selected network.');return;}setSaving(true);setNote('');try{const r=await fetch('/api/refund-wallet',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${getToken()}`},body:JSON.stringify({...wallet,confirmed:fd.get('walletConfirmed')==='on'})});const data=await r.json() as {error?:string};if(!r.ok)throw new Error(data.error);setNote('Refund wallet saved.');onSaved();}catch(e){setNote(e instanceof Error&&e.message?e.message:'Unable to save the wallet. Please try again.');}finally{setSaving(false);}}
return <form className="wallet-form" onSubmit={save}><WalletFields network={network} onNetwork={setNetwork} disabled={saving}/><button className="secondary" disabled={saving}>{saving?'Saving…':'Save refund wallet'}</button><p role="status" aria-live="polite">{note}</p></form>;}
function RefundStatus({refund}:{refund:Refund}){const breakdown=refund.amount!==null?`${usd(refund.amount)} back; ${usd(refund.fee??0)} Dodo payment fees deducted.`:'Waiting for Dodo’s confirmed fee breakdown.';
if(refund.status==='awaiting_wallet')return <p>Your refund is ready: {breakdown} Add the wallet to send it to.</p>;
if(refund.status==='awaiting_payout')return <p>Refund queued: {breakdown} It will be sent in USDC to {refund.address} on {networkName(refund.network)}.</p>;
if(refund.status==='succeeded'&&refund.reference)return <p>Refund sent: {breakdown} {refund.referenceUrl?<a href={refund.referenceUrl} target="_blank" rel="noopener noreferrer">View the transaction ↗</a>:`Reference ${refund.reference}.`}</p>;
return <p>Refund: {refund.status}. {breakdown} Bank processing times vary.</p>;}
export default function SponsorForm({selected,sponsors,enabled,reload}:{selected:number;sponsors:Sponsor[];enabled:boolean;reload:()=>void}){const [busy,setBusy]=useState(false),[message,setMessage]=useState(''),[order,setOrder]=useState<OrderState|null>(null);const [payWith,setPayWith]=useState<'card'|'stablecoin'>('card'),[network,setNetwork]=useState<RefundNetwork>('base');const token=useRef('');const [closed,setClosed]=useState(false);
const refresh=useCallback(async()=>{if(!token.current)return;try{const r=await fetch('/api/order',{headers:{Authorization:`Bearer ${token.current}`}});if(!r.ok)return;setOrder(await r.json() as OrderState);}catch{/* A polling request may fail; the next one retries. */}},[]);
useEffect(()=>{const check=()=>setClosed(Date.now()>=Date.parse(CLOSE_DATE));const first=setTimeout(check,0);const timer=setInterval(check,1000);return()=>{clearTimeout(first);clearInterval(timer);};},[]);
useEffect(()=>{try{token.current=sessionStorage.getItem(TOKEN_KEY)||'';}catch{/* Storage may be unavailable; email recovery remains available. */}if(!token.current)return;const first=setTimeout(()=>void refresh(),0);const interval=setInterval(()=>void refresh(),7000);return()=>{clearTimeout(first);clearInterval(interval);};},[refresh]);
// Celebrate a confirmed sponsorship once per browser session.
useEffect(()=>{if(order?.status!=='paid')return;const key=`slowrun-celebrated-${order.slot}`;try{if(sessionStorage.getItem(key))return;sessionStorage.setItem(key,'1');}catch{/* Celebrate anyway if storage is blocked. */}const burst=setTimeout(()=>{confetti({x:innerWidth*.12,y:innerHeight,angle:-65,count:120,power:18});confetti({x:innerWidth*.88,y:innerHeight,angle:-115,count:120,power:18});},250);return()=>clearTimeout(burst);},[order?.status,order?.slot]);
const sponsor=sponsors.find(s=>s.slot===selected);const price=nextPrice(selected,sponsor?.amount)/100;
async function checkout(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setMessage('');const fd=new FormData(event.currentTarget);const stablecoin=payWith==='stablecoin';const wallet=stablecoin?parseRefundWallet(fd.get('refundNetwork'),fd.get('refundAddress')):null;if(stablecoin&&!wallet){setMessage('Enter a valid refund wallet address for the selected network.');return;}setBusy(true);try{token.current=makeToken();sessionStorage.setItem(TOKEN_KEY,token.current);const res=await fetch('/api/checkout',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({slot:selected,version:sponsor?.version??0,brand:fd.get('brand'),tagline:fd.get('tagline'),website:fd.get('website'),rulesAccepted:fd.get('rules')==='on',token:token.current,payWith,...(wallet?{refundNetwork:wallet.network,refundAddress:wallet.address,walletConfirmed:fd.get('walletConfirmed')==='on'}:{})})});const data=await res.json() as {url:string;error:string};if(!res.ok)throw new Error(data.error);window.location.assign(data.url);}catch(e){setMessage(e instanceof Error?e.message:'Unable to start checkout. Please try again.');reload();setBusy(false);}}
async function upload(event:React.ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];if(!file)return;if(file.size>2*1024*1024){setMessage('Choose a logo under 2 MB.');return;}setBusy(true);try{const r=await fetch('/api/branding',{method:'POST',headers:{Authorization:`Bearer ${token.current}`,'Content-Type':file.type},body:file});const data=await r.json() as {error:string};if(!r.ok)throw new Error(data.error);setMessage('Your logo is published. Welcome to the club.');reload();}catch(e){setMessage(e instanceof Error?e.message:'Upload failed. Please try again.');}finally{setBusy(false);}}
const walletForm=<RefundWalletForm getToken={()=>token.current} onSaved={()=>void refresh()}/>;
return <div className="booking"><div className="booking-price">${price} <span>USD · {sponsor?'next takeover':'opening bid'}</span></div><dl className="spot-facts"><div><dt>Status</dt><dd>{sponsor?<>Held by <a href={sponsor.website} target="_blank" rel="noopener noreferrer">{sponsor.brand} ↗</a> · ${sponsor.amount/100}</>:'Open · no sponsor yet'}</dd></div><div><dt>Price to take it from you</dt><dd>${price*2} USD</dd></div><div><dt>Logos lock for printing</dt><dd>10 December 2026</dd></div></dl>{enabled&&<p className="booking-note">{sponsor?'Take over':'Claim'} this spot. The next bid will be ${price*2}. </p>}{enabled ? <form onSubmit={checkout}><label>Brand name<input name="brand" required maxLength={40} placeholder="Your company"/></label><label>One-line introduction<input name="tagline" required maxLength={100} placeholder="What are you building?"/></label><label>Website<input name="website" type="url" pattern="https://.*" required maxLength={300} placeholder="https://your-brand.com"/></label>
<fieldset className="pay-with"><legend>Pay with</legend><label className={`pay-option ${payWith==='card'?'is-selected':''}`}><input type="radio" name="payWith" value="card" checked={payWith==='card'} onChange={()=>setPayWith('card')}/><b>Card or local method</b><small>Cards, Apple Pay, Google Pay, UPI and more</small></label><label className={`pay-option ${payWith==='stablecoin'?'is-selected':''}`}><input type="radio" name="payWith" value="stablecoin" checked={payWith==='stablecoin'} onChange={()=>setPayWith('stablecoin')}/><b>Stablecoin</b><small>USDC and more · not available to buyers in India</small></label></fieldset>
{payWith==='stablecoin'&&<><p className="booking-note">If you’re outbid, your refund is sent in USDC to this wallet, minus Dodo’s payment fees. Use a wallet you control, not an exchange deposit address.</p><WalletFields network={network} onNetwork={setNetwork} disabled={busy}/></>}
<label className="check"><input name="rules" type="checkbox" required/>I accept the <a href="#detail-rules" onClick={()=>{const el=document.getElementById('detail-rules') as HTMLDetailsElement|null;if(el)el.open=true}}>auction terms, including the processing-fee deduction</a>.</label><button className="primary" disabled={!enabled||busy||closed}>{closed?'Bidding has closed':busy?'Opening checkout…':enabled?`${sponsor?'Take over':'Claim'} for $${price} →`:'Checkout opens soon'}</button></form> : <div className="interest-state"><p>Bidding opens soon. Email me if you’re interested in this spot.</p><a className="primary" href={`mailto:bhavya.gor9999@gmail.com?subject=${encodeURIComponent(`Sponsor my slow run — ${SPOTS[selected]}`)}`}>Email me about this spot</a></div>}{enabled&&<p className="booking-note">Secure checkout · Upload your logo after payment. Final holders at the December 10 cutoff get the race-day placement.</p>}
{order&&<div className="payment-state"><h4>{order.status==='paid'?`You're on the kit, ${order.brand}.`:order.status==='outbid'?'You’ve been outbid.':order.status==='unfulfilled'?'This checkout could not be fulfilled.':'Confirming your payment…'}</h4>{order.status==='paid'?<><label>Upload your logo · PNG, JPEG, WebP · up to 2 MB<input type="file" accept="image/png,image/jpeg,image/webp" disabled={busy} onChange={upload}/></label>{order.refundWallet?<p className="booking-note">If you’re outbid, your refund goes to {order.refundWallet.address} on {networkName(order.refundWallet.network)}.</p>:order.stablecoin&&<><p className="booking-note">You paid in stablecoin. Add a wallet for your refund in case you’re outbid.</p>{walletForm}</>}</>:order.refund?<><RefundStatus refund={order.refund}/>{order.refund.status==='awaiting_wallet'&&walletForm}</>:<p>We’re checking payment securely. Keep this browser tab to manage your sponsorship. Contact Bhavya if confirmation takes longer than expected.</p>}</div>}
{enabled&&<details id="detail-rules"><summary>Auction terms & refunds</summary><p>Each takeover doubles the price. If outbid, your payment is refunded minus the actual Dodo payment-processing fees. Bhavya covers additional refund fees. Stablecoin payments are refunded in USDC to the wallet you provide. Final holders at the December 10 cutoff receive the race-day placement. Unfulfilled placements receive a full refund.</p></details>}<p role="status" aria-live="polite">{message}</p></div>}
