'use client';
import {useEffect,useRef,useState} from 'react';
import {CLOSE_DATE,SPOTS,nextPrice,type Sponsor} from '@/lib/config';
const TOKEN_KEY='slow-club-checkout-token';
type OrderState={status:string;brand:string;slot:number;logo:string;refund:{status:string;amount:number|null;fee:number|null}|null};
function makeToken(){return Array.from(crypto.getRandomValues(new Uint8Array(32)),b=>b.toString(16).padStart(2,'0')).join('');}
export default function SponsorForm({selected,sponsors,enabled,reload}:{selected:number;sponsors:Sponsor[];enabled:boolean;reload:()=>void}){const [busy,setBusy]=useState(false),[message,setMessage]=useState(''),[order,setOrder]=useState<OrderState|null>(null);const token=useRef('');
useEffect(()=>{try{token.current=sessionStorage.getItem(TOKEN_KEY)||'';}catch{}if(!token.current)return;let cancelled=false;const check=async()=>{try{const r=await fetch('/api/order',{headers:{Authorization:`Bearer ${token.current}`}});if(!r.ok)return;const data=await r.json() as OrderState;if(!cancelled)setOrder(data);}catch{}};void check();const interval=setInterval(check,7000);return()=>{cancelled=true;clearInterval(interval)};},[]);
const sponsor=sponsors.find(s=>s.slot===selected);const price=nextPrice(selected,sponsor?.amount)/100;
async function checkout(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setMessage('');try{const fd=new FormData(event.currentTarget);token.current=makeToken();sessionStorage.setItem(TOKEN_KEY,token.current);const res=await fetch('/api/checkout',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({slot:selected,version:sponsor?.version??0,brand:fd.get('brand'),tagline:fd.get('tagline'),website:fd.get('website'),rulesAccepted:fd.get('rules')==='on',token:token.current})});const data=await res.json() as {url:string;error:string};if(!res.ok)throw new Error(data.error);window.location.assign(data.url);}catch(e){setMessage(e instanceof Error?e.message:'Unable to start checkout. Please try again.');reload();setBusy(false);}}
async function upload(event:React.ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];if(!file)return;if(file.size>2*1024*1024){setMessage('Choose a logo under 2 MB.');return;}setBusy(true);try{const r=await fetch('/api/branding',{method:'POST',headers:{Authorization:`Bearer ${token.current}`,'Content-Type':file.type},body:file});const data=await r.json() as {error:string};if(!r.ok)throw new Error(data.error);setMessage('Your logo is published. Welcome to the club.');reload();}catch(e){setMessage(e instanceof Error?e.message:'Upload failed. Please try again.');}finally{setBusy(false);}}
return <div className="booking"><div className="eyebrow">YOUR SELECTED SPOT</div><h3>{SPOTS[selected]}</h3>{sponsor&&<p>Currently <a href={sponsor.website} target="_blank" rel="noopener noreferrer"><b>{sponsor.brand} ↗</b></a> · ${sponsor.amount/100}</p>}<div className="booking-price">${price} <span>USD · {sponsor?'next takeover':'opening bid'}</span></div><p className="booking-note">{sponsor?'Take over':'Claim'} this spot. The next bid will be ${price*2}. If you’re outbid, you get your payment back minus Dodo payment-processing fees.</p><form onSubmit={checkout}><label>Brand name<input name="brand" required maxLength={40} placeholder="Your company"/></label><label>One-line introduction<input name="tagline" required maxLength={100} placeholder="What are you building?"/></label><label>Website<input name="website" type="url" pattern="https://.*" required maxLength={300} placeholder="https://your-brand.com"/></label><label className="check"><input name="rules" type="checkbox" required/>I accept the <a href="#rules" onClick={()=>{const el=document.getElementById('rules') as HTMLDetailsElement|null;if(el)el.open=true}}>auction terms and fee deduction</a>.</label><button className="primary" disabled={!enabled||busy||Date.now()>=Date.parse(CLOSE_DATE)}>{busy?'Opening checkout…':enabled?`${sponsor?'Take over':'Claim'} for $${price} ↗`:'Checkout opens soon'}</button></form>{!enabled&&<p className="booking-note"><a href={`mailto:bhavya.gor9999@gmail.com?subject=${encodeURIComponent(`Slow Club sponsorship — ${SPOTS[selected]}`)}`}>Email Bhavya about this spot ↗</a></p>}<p className="booking-note">Dodo secure checkout · Upload your logo after payment. Final holders at the December 10 cutoff get the race-day placement.</p>{order&&<div className="payment-state"><h4>{order.status==='paid'?`You're on the kit, ${order.brand}.`:order.status==='outbid'?'You’ve been outbid.':order.status==='unfulfilled'?'This checkout could not be fulfilled.':'Confirming your payment…'}</h4>{order.status==='paid'?<label>Upload your logo · PNG, JPEG, WebP · up to 2 MB<input type="file" accept="image/png,image/jpeg,image/webp" disabled={busy} onChange={upload}/></label>:order.refund?<p>Refund: {order.refund.status}. {order.refund.amount!==null?`$${(order.refund.amount/100).toFixed(2)} back; $${((order.refund.fee??0)/100).toFixed(2)} Dodo payment fees deducted.`:'Waiting for Dodo’s confirmed fee breakdown.'} Bank processing times vary.</p>:<p>We’re checking payment securely. Keep this browser tab to manage your sponsorship. Contact Bhavya if confirmation takes longer than expected.</p>}</div>}<p role="status" aria-live="polite">{message}</p></div>}
