import {refundAfterFees,type PaymentFee} from './refund-math';
import {db,dodo,settings} from './server';
type RefundJob={payment:string;mode:string;status:string;amount:number|null;fee:number|null;refund_id:string|null};
export async function processRefund(paymentId:string){const {data:job,error:loadError}=await db().from('slowrun_refund_jobs').select('*').eq('payment',paymentId).maybeSingle<RefundJob>();if(loadError)throw loadError;if(!job||job.status==='succeeded'||job.status==='submitted')return;if(job.status==='failed')throw new Error('Refund requires operator review');const client=dodo();
if(job.amount===null){const payment=await client.payments.retrieve(paymentId,{timeout:10000,maxRetries:1});if(payment.currency!=='USD')throw new Error('Refund currency mismatch');if(payment.refunds.length)throw new Error('Existing refund requires reconciliation');let fee=0;if(job.mode==='outbid'){const entries:PaymentFee[]=[];for await(const entry of client.balances.retrieveLedger({reference_object_id:paymentId,event_type:'payment_fees',page_size:100},{timeout:10000,maxRetries:1})){entries.push(entry);}fee=refundAfterFees(payment.total_amount,paymentId,entries).fee;}const amount=payment.total_amount-fee;
// Freeze the amount once; a concurrent run that got here first keeps its value.
const {error:freezeError}=await db().from('slowrun_refund_jobs').update({amount,fee}).eq('payment',paymentId).is('amount',null);if(freezeError)throw freezeError;}
const {data:fixed,error:fixedError}=await db().from('slowrun_refund_jobs').select('amount,fee').eq('payment',paymentId).single<{amount:number;fee:number}>();if(fixedError||!fixed)throw fixedError??new Error('Missing refund');const refund=await client.refunds.create({payment_id:paymentId,items:[{item_id:settings().DODO_PAYMENTS_PRODUCT_ID,amount:fixed.amount,tax_inclusive:true}],reason:job.mode==='outbid'?'Outbid on a Slow Club placement. Original payment refunded minus the actual Dodo payment-processing fees.':'Checkout could not be fulfilled; full refund.',metadata:{project:'slow-club',payment:paymentId}},{idempotencyKey:`slow_refund_${paymentId}`,timeout:10000,maxRetries:1});
const {error:idError}=await db().from('slowrun_refund_jobs').update({refund_id:refund.refund_id}).eq('payment',paymentId);if(idError)throw idError;
// A refund webhook may already have marked it succeeded; never downgrade that.
const {error:statusError}=await db().from('slowrun_refund_jobs').update({status:'submitted'}).eq('payment',paymentId).neq('status','succeeded');if(statusError)throw statusError;}
export async function drainRefunds(){const {data,error:loadError}=await db().from('slowrun_refund_jobs').select('payment').eq('status','pending').order('created').limit(10);if(loadError)throw loadError;for(const job of data??[])await processRefund(job.payment);}
