import {z} from 'zod';
import {db,dodo,ready,settings,hash,error,sameOrigin,limited,readJson} from '@/lib/server';
import {CLOSE_DATE,nextPrice,SPOTS} from '@/lib/config';
import {baseSettings} from '@/lib/base';
import {formatUsdc,randomTag,usdcUnits} from '@/lib/usdc';
import {parseRefundWallet} from '@/lib/wallet';
const clean=z.string().trim().min(1).refine(v=>![...v].some(c=>c.charCodeAt(0)<32||c.charCodeAt(0)===127),'Control characters are not allowed');
const schema=z.object({slot:z.number().int().min(0).max(SPOTS.length-1),version:z.number().int().min(0),brand:clean.pipe(z.string().max(40)),tagline:clean.pipe(z.string().max(100)),website:z.url().max(300).refine(v=>{const u=new URL(v);return u.protocol==='https:'&&!u.username&&!u.password;}),rulesAccepted:z.literal(true),token:z.string().regex(/^[a-f0-9]{64}$/),payWith:z.enum(['card','stablecoin','base']).default('card'),refundNetwork:z.string().max(20).optional(),refundAddress:z.string().max(64).optional(),walletConfirmed:z.boolean().optional()});
type Previous={status:string;checkout_url:string|null;expires:number;pay_with:string;base_amount:number|null};
// Base Pay orders get their exact USDC amount (price + sub-cent tag); two pending orders never share one.
async function tagBaseOrder(id:string,cents:number){for(let attempt=0;attempt<5;attempt++){const units=usdcUnits(cents,randomTag());const {error:tagError}=await db().from('slowrun_orders').update({base_amount:Number(units)}).eq('id',id);if(!tagError)return units;if(tagError.code!=='23505')throw tagError;}throw new Error('Could not tag the Base payment');}
const basePayload=(units:bigint)=>{const s=baseSettings();return {amount:formatUsdc(units),to:s.recipient,testnet:s.testnet};};
export async function POST(req:Request){if(!sameOrigin(req))return error('Invalid origin',403);if(!ready())return error('Sponsorship checkout is opening soon. No payment has been taken.',503);if(Date.now()>=Date.parse(CLOSE_DATE))return error('Sponsorships have closed.',409);
try{if(await limited(req,'checkout'))return error('Please wait a minute before trying again.',429);const parsed=schema.safeParse(await readJson(req));if(!parsed.success)return error('Check your brand details, HTTPS website, and auction terms.');const p=parsed.data;
const onBase=p.payWith==='base';if(onBase&&!baseSettings().recipient)return error('USDC payments on Base are opening soon. Choose card for now.',503);
// Dodo's refund API has no destination field, so a Dodo stablecoin bid must carry the wallet its refund goes to.
const stablecoin=p.payWith==='stablecoin';const wallet=stablecoin?parseRefundWallet(p.refundNetwork,p.refundAddress):null;if(stablecoin&&(!wallet||p.walletConfirmed!==true))return error('Add a refund wallet you control on a supported network, and confirm it.');const tokenHash=await hash(p.token);
const {data:previous,error:previousError}=await db().from('slowrun_orders').select('status,checkout_url,expires,pay_with,base_amount').eq('id',tokenHash).maybeSingle<Previous>();if(previousError)throw previousError;if(previous){if(previous.status==='pending'&&previous.expires>Date.now()){if(previous.pay_with==='base'&&previous.base_amount)return Response.json({base:basePayload(BigInt(previous.base_amount))});if(previous.checkout_url)return Response.json({url:previous.checkout_url});}return error('This attempt is already processing or has expired.',409);}
const now=Date.now(),expires=Math.min(now+30*60*1000,Date.parse(CLOSE_DATE)),id=tokenHash;
const {data:slot,error:slotError}=await db().from('slowrun_slots').select('version,owner_id').eq('id',p.slot).single<{version:number;owner_id:string|null}>();if(slotError)throw slotError;if(slot.version!==p.version)return error('This spot has a new price. Refresh and try again.',409);
let ownerAmount:number|undefined;if(slot.owner_id){const {data:owner,error:ownerError}=await db().from('slowrun_orders').select('amount').eq('id',slot.owner_id).single<{amount:number}>();if(ownerError)throw ownerError;ownerAmount=owner.amount;}
const amount=nextPrice(p.slot,ownerAmount);if(!Number.isSafeInteger(amount)||amount>100000000)return error('Please contact Bhavya for this sponsorship.',409);
// The reservation re-checks the version under a row lock, so the price computed above is still the current one.
const {data:reserved,error:reserveError}=await db().rpc('slowrun_reserve_slot',{p_order_id:id,p_slot:p.slot,p_version:p.version,p_amount:amount,p_brand:p.brand,p_tagline:p.tagline,p_website:p.website,p_token_hash:tokenHash,p_now:now,p_expires:expires,p_pay_with:p.payWith,p_refund_network:wallet?.network??null,p_refund_address:wallet?.address??null});if(reserveError)throw reserveError;
if(reserved==='stale')return error('This spot has a new price. Refresh and try again.',409);if(reserved!=='reserved')return error('Someone is checking out this spot. Please try again shortly.',409);
if(onBase){try{return Response.json({base:basePayload(await tagBaseOrder(id,amount))});}catch{await db().from('slowrun_slots').update({reserved_until:0}).eq('order_id',id);return error('Base checkout could not be opened. Please try again.',502);}}
try{const e=settings();const checkout=await dodo().checkoutSessions.create({product_cart:[{product_id:e.DODO_PAYMENTS_PRODUCT_ID,quantity:1,amount}],return_url:`${e.SITE_URL}/?checkout=returned`,metadata:{project:'slow-club',orderId:id},billing_currency:'USD',feature_flags:{allow_currency_selection:false,allow_discount_code:false},...(stablecoin?{allowed_payment_method_types:['crypto_currency' as const]}:{})},{idempotencyKey:id,maxRetries:1,timeout:10000});if(!checkout.checkout_url)throw new Error('Missing checkout');const {error:saveError}=await db().from('slowrun_orders').update({session:checkout.session_id,checkout_url:checkout.checkout_url}).eq('id',id);if(saveError)throw saveError;return Response.json({url:checkout.checkout_url});}catch{await db().from('slowrun_slots').update({reserved_until:0}).eq('order_id',id);return error('Checkout could not be opened. Please try again.',502);}
}catch{return error('Unable to start checkout. Check your details and try again.',400);}}
