import {z} from 'zod';
import {db,dodo,ready,settings,hash,error,sameOrigin,limited,readJson} from '@/lib/server';
import {CLOSE_DATE,nextPrice,SPOTS} from '@/lib/config';
const clean=z.string().trim().min(1).regex(/^[^\x00-\x1f\x7f]+$/);
const schema=z.object({slot:z.number().int().min(0).max(SPOTS.length-1),version:z.number().int().min(0),brand:clean.max(40),tagline:clean.max(100),website:z.url().max(300).refine(v=>{const u=new URL(v);return u.protocol==='https:'&&!u.username&&!u.password;}),rulesAccepted:z.literal(true),token:z.string().regex(/^[a-f0-9]{64}$/)});
export async function POST(req:Request){if(!sameOrigin(req))return error('Invalid origin',403);if(!ready())return error('Sponsorship checkout is opening soon. No payment has been taken.',503);if(Date.now()>=Date.parse(CLOSE_DATE))return error('Sponsorships have closed.',409);
try{if(await limited(req,'checkout'))return error('Please wait a minute before trying again.',429);const parsed=schema.safeParse(await readJson(req));if(!parsed.success)return error('Check your brand details, HTTPS website, and auction terms.');const p=parsed.data;const tokenHash=await hash(p.token);const previous=await db().prepare('SELECT status,checkout_url,expires FROM orders WHERE id=?').bind(tokenHash).first<{status:string;checkout_url:string;expires:number}>();if(previous){if(previous.status==='pending'&&previous.checkout_url&&previous.expires>Date.now())return Response.json({url:previous.checkout_url});return error('This attempt is already processing or has expired.',409);}
const now=Date.now(),expires=Math.min(now+30*60*1000,Date.parse(CLOSE_DATE)),id=tokenHash;await db().prepare('INSERT OR IGNORE INTO slots (id, reserved_until, paid,version) VALUES (?,0,0,0)').bind(p.slot).run();
const slot=await db().prepare('SELECT s.version,s.owner_id,o.amount FROM slots s LEFT JOIN orders o ON s.owner_id=o.id WHERE s.id=?').bind(p.slot).first<{version:number;owner_id:string|null;amount:number|null}>();if(!slot||slot.version!==p.version)return error('This spot has a new price. Refresh and try again.',409);const amount=nextPrice(p.slot,slot.amount??undefined);if(!Number.isSafeInteger(amount)||amount>100000000)return error('Please contact Bhavya for this sponsorship.',409);
const locked=await db().prepare('UPDATE slots SET order_id=?,reserved_until=? WHERE id=? AND version=? AND reserved_until<?').bind(id,expires,p.slot,p.version,now).run();if(locked.meta.changes!==1)return error('Someone is checking out this spot. Please try again shortly.',409);
await db().prepare("INSERT INTO orders (id,slot,amount,brand,tagline,website,token_hash,status,expires,created,expected_version,previous_id) VALUES (?,?,?,?,?,?,?,'pending',?,?,?,?)").bind(id,p.slot,amount,p.brand,p.tagline,p.website,tokenHash,expires,now,p.version,slot.owner_id).run();
try{const e=settings();const checkout=await dodo().checkoutSessions.create({product_cart:[{product_id:e.DODO_PAYMENTS_PRODUCT_ID,quantity:1,amount}],return_url:`${e.SITE_URL}/?checkout=returned`,metadata:{project:'slow-club',orderId:id},billing_currency:'USD',feature_flags:{allow_currency_selection:false,allow_discount_code:false}},{idempotencyKey:id,maxRetries:1,timeout:10000});if(!checkout.checkout_url)throw new Error('Missing checkout');await db().prepare('UPDATE orders SET session=?,checkout_url=? WHERE id=?').bind(checkout.session_id,checkout.checkout_url,id).run();return Response.json({url:checkout.checkout_url});}catch{await db().prepare('UPDATE slots SET reserved_until=0 WHERE order_id=?').bind(id).run();return error('Checkout could not be opened. Please try again.',502);}
}catch{return error('Unable to start checkout. Check your details and try again.',400);}}
