import {cp,mkdir,rm,writeFile} from 'node:fs/promises';
import {spawnSync} from 'node:child_process';
const stage=new URL('../.vercel-next/',import.meta.url);
await rm(stage,{recursive:true,force:true});
await mkdir(new URL('app/api/[...path]/',stage),{recursive:true});
await mkdir(new URL('lib/',stage),{recursive:true});
for(const file of ['page.tsx','layout.tsx','globals.css','Arena.tsx','RaceStart.ts','SponsorForm.tsx'])await cp(new URL(`../app/${file}`,import.meta.url),new URL(`app/${file}`,stage));
await cp(new URL('../lib/config.ts',import.meta.url),new URL('lib/config.ts',stage));
await cp(new URL('../lib/avatar.mjs',import.meta.url),new URL('lib/avatar.mjs',stage));
await cp(new URL('../vercel-adapter/route.ts',import.meta.url),new URL('app/api/[...path]/route.ts',stage));
await cp(new URL('../public/',import.meta.url),new URL('public/',stage),{recursive:true});
await cp(new URL('../postcss.config.mjs',import.meta.url),new URL('postcss.config.mjs',stage));
await writeFile(new URL('package.json',stage),JSON.stringify({name:'slow-club-vercel',private:true,type:'module'}));
await writeFile(new URL('tsconfig.json',stage),JSON.stringify({compilerOptions:{allowJs:true,target:'ES2017',lib:['dom','dom.iterable','esnext'],strict:true,noEmit:true,skipLibCheck:true,esModuleInterop:true,module:'esnext',moduleResolution:'bundler',resolveJsonModule:true,isolatedModules:true,jsx:'react-jsx',plugins:[{name:'next'}],paths:{'@/*':['./*']}},include:['next-env.d.ts','**/*.ts','**/*.tsx','.next/types/**/*.ts'],exclude:['node_modules']}));
await writeFile(new URL('next.config.mjs',stage),`import path from 'node:path';\nexport default {outputFileTracingRoot:path.resolve(process.cwd()),async headers(){return [{source:'/(.*)',headers:[{key:'X-Content-Type-Options',value:'nosniff'},{key:'Referrer-Policy',value:'strict-origin-when-cross-origin'},{key:'Permissions-Policy',value:'camera=(), microphone=(), geolocation=()'}]}]}};\n`);
const result=spawnSync(process.execPath,['node_modules/next/dist/bin/next','build','.vercel-next','--webpack'],{stdio:'inherit',env:process.env});
process.exit(result.status??1);
